### ISSUE TITLE
Syntax highlighting for Go

### ISSUE THREAD

**Issue by 7AC** [tomaswolf/gerrit-gitblit-plugin#10] opened 2015-10-22 06:07 UTC
Syntax highlighting seems to work perfectly for most languages, however I can't get it to work for Go (golang). I do see that the jar I downloaded contains `com/gitblit/wicket/pages/prettify/lang-go.js`. I'm using Gerrit 2.11.4 and `gitblit-plugin-2.11.3.162.2.jar`. Thank you for the awesome plugin btw!

**Comment by tomaswolf** [comment] 2015-10-22 19:52
What extension do your Go files have?

**Comment by 7AC** [comment] 2015-10-22 20:11
They all have `.go`.

**Comment by tomaswolf** [comment] 2015-10-22 20:58
Works for me. Please note that the [syntax coloring for Go](https://github.com/google/code-prettify/blob/master/src/lang-go.js) in prettify is _very_ minimal. It appears it only color comments.

**Comment by 7AC** [comment] 2015-10-22 21:13
Interesting... If I run their `run_prettify.js` directly on this:

```html
<html>
<body>
   <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
   <pre class="prettyprint lang-go">// No copyright
package foo
 
import (
   "bar"
)
 
// Baz is a type
type Baz int</pre>
</body>
</html>
```

I end up with:

```html
<html><head><link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/google/code-prettify/master/loader/prettify.css"></head><body>
   
   <pre class="prettyprint lang-go prettyprinted" style=""><span class="com">// No copyright</span><span class="pln">
</span><span class="kwd">package</span><span class="pln"> foo
 
</span><span class="kwd">import</span><span class="pln"> </span><span class="pun">(</span><span class="pln">
   </span><span class="str">"bar"</span><span class="pln">
</span><span class="pun">)</span><span class="pln">
 
</span><span class="com">// Baz is a type</span><span class="pln">
type </span><span class="typ">Baz</span><span class="pln"> </span><span class="kwd">int</span></pre>


</body></html>
```

**Comment by tomaswolf** [comment] 2015-10-22 21:45
Strange indeed... I'll have to analyze this some more in the next days.

**Comment by tomaswolf** [comment] 2015-10-25 21:02
No idea why run_prettify.js gives something different than prettify.js. Might just as well be a bug in run_prettify, or maybe not. I haven't analyzed the internals of this prettify thing. I find it bizarre that some (apparently java?) keywords are recognized in the snippet you posted above, but "type" for instance isn't. The lang-go.js has _no_ keywords defined at all. Maybe something is leaking through that shouldn't.

Whatever. I've changed the plugin to include an updated prettify, and to use run_prettify, and now Gitblit produces the same syntax coloring as above. Give release [v2.11.3.162.3](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.11.3.162.3) a try; if it solves the problem for you, too, I'll promote that from prerelease to release.

To clarify: the plugin does **not** pull in prettify from cdn.rawgit.com; it includes its own copy. Helps avoid trouble when running behind strange corporate firewalls that block cdn.rawgit.com.

**Comment by 7AC** [comment] 2015-10-26 18:10
You're right, same goes for `func`. I agree with you this seems like a bug in code-prettify rather than a feature, I should take the time to write my own Go lexer and post a merge request. Thanks for looking into this!

**Comment by tomaswolf** [comment] 2015-10-27 20:07
The point is that you didn't specify any language in your run_prettify URL. Since go isn't one of the built-in languages, prettify doesn't have the go syntax coloring and falls back to a default coloring, which has some common keywords.

If you invoke run_prettify via the URL https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?lang=go you will get the defined syntax highlighting for the go language, which, as I pointed out above, is very minimal and is what plugin v2.11.3.162.2 shows. This minimal syntax coloring is by design in prettify, and everything in Gitblit and in the plugin thus was working correctly.

I'll delete the v2.11.3.162.3 pre-release of the gerrit-gitblit-plugin., and close this issue as invalid.

**Closed by tomaswolf** 2015-10-27 20:07 UTC
